export const destinations = [
  {
    name: "Spain",
    latitude: 40.4637,
    longitude: -3.7492,
    sea: true,
    mountains: true,
    photo: "https://img.sandayagroupe.eu/images/7/9/5/6/666597-1-fre-FR/1e1cc587a560-Espagne.jpg",
    description: "A vibrant country known for its sunny beaches, rich culture, and lively cities like Barcelona and Madrid.",
    avgDailyBudget: 90,
    countryCode: "ES",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 11 },
      { month: "February", avgTemp: 12 },
      { month: "March", avgTemp: 15 },
      { month: "April", avgTemp: 17 },
      { month: "May", avgTemp: 21 },
      { month: "June", avgTemp: 25 },
      { month: "July", avgTemp: 29 },
      { month: "August", avgTemp: 29 },
      { month: "September", avgTemp: 26 },
      { month: "October", avgTemp: 21 },
      { month: "November", avgTemp: 15 },
      { month: "December", avgTemp: 12 },
    ],
  },
  {
    name: "Italy",
    latitude: 41.8719,
    longitude: 12.5674,
    sea: true,
    mountains: true,
    photo: "https://images.travelandleisureasia.com/wp-content/uploads/sites/3/2024/03/13124410/Venice-1-1600x900.jpg",
    description: "Famous for its history, delicious cuisine, and stunning cities like Rome, Venice, and Florence.",
    avgDailyBudget: 110,
    countryCode: "IT",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 8 },
      { month: "February", avgTemp: 9 },
      { month: "March", avgTemp: 13 },
      { month: "April", avgTemp: 17 },
      { month: "May", avgTemp: 22 },
      { month: "June", avgTemp: 26 },
      { month: "July", avgTemp: 30 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 26 },
      { month: "October", avgTemp: 20 },
      { month: "November", avgTemp: 14 },
      { month: "December", avgTemp: 10 },
    ],
  },
  {
    name: "France",
    latitude: 46.2276,
    longitude: 2.2137,
    sea: true,
    mountains: true,
    photo: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    description: "A romantic destination offering world-class cuisine, iconic landmarks, and beautiful countryside.",
    avgDailyBudget: 130,
    countryCode: "FR",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 5 },
      { month: "February", avgTemp: 6 },
      { month: "March", avgTemp: 10 },
      { month: "April", avgTemp: 14 },
      { month: "May", avgTemp: 18 },
      { month: "June", avgTemp: 22 },
      { month: "July", avgTemp: 25 },
      { month: "August", avgTemp: 25 },
      { month: "September", avgTemp: 21 },
      { month: "October", avgTemp: 16 },
      { month: "November", avgTemp: 10 },
      { month: "December", avgTemp: 6 },
    ],
  },
  {
    name: "Germany",
    latitude: 51.1657,
    longitude: 10.4515,
    sea: false,
    mountains: true,
    photo: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b",
    description: "A mix of modern cities, historic towns, and scenic landscapes with mountains and forests.",
    avgDailyBudget: 100,
    countryCode: "DE",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 2 },
      { month: "February", avgTemp: 3 },
      { month: "March", avgTemp: 8 },
      { month: "April", avgTemp: 12 },
      { month: "May", avgTemp: 17 },
      { month: "June", avgTemp: 20 },
      { month: "July", avgTemp: 23 },
      { month: "August", avgTemp: 23 },
      { month: "September", avgTemp: 18 },
      { month: "October", avgTemp: 13 },
      { month: "November", avgTemp: 7 },
      { month: "December", avgTemp: 3 },
    ],
  },
  {
    name: "Norway",
    latitude: 60.4720,
    longitude: 8.4689,
    sea: true,
    mountains: true,
    photo: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    description: "Known for its breathtaking fjords, northern lights, and dramatic natural landscapes.",
    avgDailyBudget: 180,
    countryCode: "NO",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Schengen travel insurance"],
      notes: "EEA citizens can enter with ID card. Part of Schengen Area."
    },
    months: [
      { month: "January", avgTemp: -5 },
      { month: "February", avgTemp: -4 },
      { month: "March", avgTemp: 0 },
      { month: "April", avgTemp: 5 },
      { month: "May", avgTemp: 10 },
      { month: "June", avgTemp: 14 },
      { month: "July", avgTemp: 16 },
      { month: "August", avgTemp: 15 },
      { month: "September", avgTemp: 11 },
      { month: "October", avgTemp: 6 },
      { month: "November", avgTemp: 1 },
      { month: "December", avgTemp: -3 },
    ],
  },
  {
    name: "Sweden",
    latitude: 60.1282,
    longitude: 18.6435,
    sea: true,
    mountains: true,
    photo: "https://www.intrepidtravel.com/adventures/wp-content/uploads/2023/09/Europe-Sweden-Stockholm-city-151426785-getty-pa.jpg",
    description: "A peaceful country with beautiful nature, clean cities, and a high quality of life.",
    avgDailyBudget: 160,
    countryCode: "SE",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Schengen travel insurance"],
      notes: "EU/EEA citizens can enter with ID card. Part of Schengen Area."
    },
    months: [
      { month: "January", avgTemp: -3 },
      { month: "February", avgTemp: -2 },
      { month: "March", avgTemp: 2 },
      { month: "April", avgTemp: 7 },
      { month: "May", avgTemp: 13 },
      { month: "June", avgTemp: 17 },
      { month: "July", avgTemp: 20 },
      { month: "August", avgTemp: 19 },
      { month: "September", avgTemp: 14 },
      { month: "October", avgTemp: 9 },
      { month: "November", avgTemp: 4 },
      { month: "December", avgTemp: -1 },
    ],
  },
  {
    name: "Greece",
    latitude: 39.0742,
    longitude: 21.8243,
    sea: true,
    mountains: true,
    photo: "https://clickstay.s3-eu-west-1.amazonaws.com/images/blog/post/1santorini.jpg",
    description: "A perfect mix of ancient history, crystal-clear seas, and sunny island life.",
    avgDailyBudget: 85,
    countryCode: "GR",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 10 },
      { month: "February", avgTemp: 11 },
      { month: "March", avgTemp: 14 },
      { month: "April", avgTemp: 18 },
      { month: "May", avgTemp: 23 },
      { month: "June", avgTemp: 28 },
      { month: "July", avgTemp: 32 },
      { month: "August", avgTemp: 32 },
      { month: "September", avgTemp: 28 },
      { month: "October", avgTemp: 22 },
      { month: "November", avgTemp: 17 },
      { month: "December", avgTemp: 12 },
    ],
  },
  {
    name: "Turkey",
    latitude: 38.9637,
    longitude: 35.2433,
    sea: true,
    mountains: true,
    photo: "https://media.worldnomads.com/Explore/middle-east/hagia-sophia-church-istanbul-turkey-gettyimages-skaman306.jpg",
    description: "A unique blend of cultures, offering stunning coastlines, historic sites, and vibrant markets.",
    avgDailyBudget: 60,
    countryCode: "TR",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "Many nationalities can obtain e-Visa on arrival or online"
    },
    months: [
      { month: "January", avgTemp: 6 },
      { month: "February", avgTemp: 7 },
      { month: "March", avgTemp: 11 },
      { month: "April", avgTemp: 17 },
      { month: "May", avgTemp: 22 },
      { month: "June", avgTemp: 27 },
      { month: "July", avgTemp: 31 },
      { month: "August", avgTemp: 31 },
      { month: "September", avgTemp: 27 },
      { month: "October", avgTemp: 21 },
      { month: "November", avgTemp: 15 },
      { month: "December", avgTemp: 9 },
    ],
  },
  {
    name: "Thailand",
    latitude: 15.8700,
    longitude: 100.9925,
    sea: true,
    mountains: false,
    photo: "https://media.istockphoto.com/id/2149112736/photo/wat-arun-temple-at-sunset-bangkok-in-thailand.jpg?s=612x612&w=0&k=20&c=1JqYAueTVDWfnj8iwCRlS_VIp-3YBeDp6Wp-Pq19qVk=",
    description: "A tropical paradise with beautiful beaches, rich culture, and amazing street food.",
    avgDailyBudget: 50,
    countryCode: "TH",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Proof of funds"],
      notes: "Many nationalities get 30-day visa exemption. Can apply for e-Visa."
    },
    months: [
      { month: "January", avgTemp: 30 },
      { month: "February", avgTemp: 31 },
      { month: "March", avgTemp: 33 },
      { month: "April", avgTemp: 34 },
      { month: "May", avgTemp: 32 },
      { month: "June", avgTemp: 31 },
      { month: "July", avgTemp: 30 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 29 },
      { month: "October", avgTemp: 29 },
      { month: "November", avgTemp: 30 },
      { month: "December", avgTemp: 29 },
    ],
  },
  {
    name: "Japan",
    latitude: 36.2048,
    longitude: 138.2529,
    sea: true,
    mountains: true,
    photo: "https://i0.wp.com/www.touristjapan.com/wp-content/uploads/2023/04/fujiyoshida-view-scaled-e1680427764989.jpg?resize=2000%2C800&ssl=1",
    description: "A fascinating mix of tradition and technology, with temples, nature, and modern cities.",
    avgDailyBudget: 120,
    countryCode: "JP",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket"],
      notes: "Many nationalities get 90-day temporary visitor status on arrival"
    },
    months: [
      { month: "January", avgTemp: 5 },
      { month: "February", avgTemp: 6 },
      { month: "March", avgTemp: 10 },
      { month: "April", avgTemp: 16 },
      { month: "May", avgTemp: 21 },
      { month: "June", avgTemp: 24 },
      { month: "July", avgTemp: 28 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 26 },
      { month: "October", avgTemp: 20 },
      { month: "November", avgTemp: 14 },
      { month: "December", avgTemp: 9 },
    ],
  },
  {
    name: "Australia",
    latitude: -25.2744,
    longitude: 133.7751,
    sea: true,
    mountains: true,
    photo: "https://www.planetware.com/img/gallery/australias-top-10-scenic-destinations-to-snap-stunning-pictures/l-intro-1760706512.jpg",
    description: "A vast country known for its beaches, wildlife, and iconic cities like Sydney and Melbourne.",
    avgDailyBudget: 170,
    countryCode: "AU",
    visaRequirements: {
      visaRequired: true,
      passportValidityMonths: 6,
      documents: ["Valid passport", "eVisitor visa or ETA", "Travel insurance (recommended)"],
      notes: "eVisitor (subclass 651) is the most common visa for tourists"
    },
    months: [
      { month: "January", avgTemp: 30 },
      { month: "February", avgTemp: 30 },
      { month: "March", avgTemp: 27 },
      { month: "April", avgTemp: 23 },
      { month: "May", avgTemp: 19 },
      { month: "June", avgTemp: 16 },
      { month: "July", avgTemp: 15 },
      { month: "August", avgTemp: 17 },
      { month: "September", avgTemp: 20 },
      { month: "October", avgTemp: 24 },
      { month: "November", avgTemp: 27 },
      { month: "December", avgTemp: 29 },
    ],
  },
  {
    name: "Canada",
    latitude: 56.1304,
    longitude: -106.3468,
    sea: true,
    mountains: true,
    photo: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    description: "A nature lover’s dream with vast forests, mountains, and friendly multicultural cities.",
    avgDailyBudget: 140,
    countryCode: "CA",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Proof of funds"],
      notes: "Many nationalities can enter visa-free. Check if you need an eTA."
    },
    months: [
      { month: "January", avgTemp: -10 },
      { month: "February", avgTemp: -8 },
      { month: "March", avgTemp: -2 },
      { month: "April", avgTemp: 6 },
      { month: "May", avgTemp: 13 },
      { month: "June", avgTemp: 18 },
      { month: "July", avgTemp: 22 },
      { month: "August", avgTemp: 21 },
      { month: "September", avgTemp: 16 },
      { month: "October", avgTemp: 9 },
      { month: "November", avgTemp: 2 },
      { month: "December", avgTemp: -6 },
    ],
  },
  {
    name: "Brazil",
    latitude: -14.2350,
    longitude: -51.9253,
    sea: true,
    mountains: false,
    photo: "https://blog.onevasco.com/wp-content/uploads/Reasons-to-Visit-Brazil.png",
    description: "A lively destination with tropical beaches, vibrant culture, and famous festivals like Carnival.",
    avgDailyBudget: 70,
    countryCode: "BR",
    visaRequirements: {
      visaRequired: true,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Tourist visa", "Return ticket", "Proof of funds"],
      notes: "Many nationalities need a visa. Processing typically takes 1-2 weeks."
    },
    months: [
      { month: "January", avgTemp: 30 },
      { month: "February", avgTemp: 30 },
      { month: "March", avgTemp: 29 },
      { month: "April", avgTemp: 28 },
      { month: "May", avgTemp: 26 },
      { month: "June", avgTemp: 25 },
      { month: "July", avgTemp: 25 },
      { month: "August", avgTemp: 26 },
      { month: "September", avgTemp: 27 },
      { month: "October", avgTemp: 28 },
      { month: "November", avgTemp: 29 },
      { month: "December", avgTemp: 30 },
    ],
  },
  {
    name: "Portugal",
    latitude: 39.3999,
    longitude: -8.2245,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/2169728903/photo/beautiful-view-of-the-city-of-porto-on-a-beautiful-summer-day-porto-portugal.jpg?s=612x612&w=0&k=20&c=DYcsyqlULz2VS_yoIBTmm1ft_z-Hu-RlG6nMksiUkwQ=",
    description: "A charming European destination with sunny beaches, historic towns, and delicious seafood.",
    avgDailyBudget: 85,
    countryCode: "PT",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card"
    },
    months: [
      { month: "January", avgTemp: 11 },
      { month: "February", avgTemp: 12 },
      { month: "March", avgTemp: 15 },
      { month: "April", avgTemp: 17 },
      { month: "May", avgTemp: 20 },
      { month: "June", avgTemp: 24 },
      { month: "July", avgTemp: 27 },
      { month: "August", avgTemp: 27 },
      { month: "September", avgTemp: 24 },
      { month: "October", avgTemp: 20 },
      { month: "November", avgTemp: 15 },
      { month: "December", avgTemp: 12 },
    ],
  },
  {
    name: "Iceland",
    latitude: 64.9631,
    longitude: -19.0208,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/1629533738/photo/godafoss-waterfall-flowing-with-colorful-sunset-sky-and-male-tourist-standing-on-cliff-in.jpg?s=612x612&w=0&k=20&c=oKRdh9yZhabi7PLMAalqQa2GrV_DcwrViH38cxCGGo0=",
    description: "A unique land of volcanoes, glaciers, and northern lights, perfect for nature and adventure lovers.",
    avgDailyBudget: 150,
    countryCode: "IS",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Schengen travel insurance"],
      notes: "EEA citizens can enter with ID card. Part of Schengen Area."
    },
    months: [
      { month: "January", avgTemp: -1 },
      { month: "February", avgTemp: 0 },
      { month: "March", avgTemp: 1 },
      { month: "April", avgTemp: 3 },
      { month: "May", avgTemp: 7 },
      { month: "June", avgTemp: 11 },
      { month: "July", avgTemp: 13 },
      { month: "August", avgTemp: 13 },
      { month: "September", avgTemp: 10 },
      { month: "October", avgTemp: 6 },
      { month: "November", avgTemp: 2 },
      { month: "December", avgTemp: -1 },
    ],
  },
  {
    name: "Vietnam",
    latitude: 14.0583,
    longitude: 108.2772,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/1560636412/photo/panoramic-of-ho-chi-minh-city-or-saigon-city-at-twilight-in-vietnam.jpg?s=612x612&w=0&k=20&c=ZNki-NDTLSPKI0nKSCCcM_Lenr40Zw-sizr8ms6bhyI=",
    description: "A vibrant Asian country with lush landscapes, historic cities, and great street food.",
    avgDailyBudget: 55,
    countryCode: "VN",
    visaRequirements: {
      visaRequired: true,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Tourist visa or e-Visa", "Passport photos"],
      notes: "e-Visa available online for many nationalities. Processing: 1-3 days."
    },
    months: [
      { month: "January", avgTemp: 20 },
      { month: "February", avgTemp: 22 },
      { month: "March", avgTemp: 25 },
      { month: "April", avgTemp: 28 },
      { month: "May", avgTemp: 30 },
      { month: "June", avgTemp: 31 },
      { month: "July", avgTemp: 30 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 29 },
      { month: "October", avgTemp: 27 },
      { month: "November", avgTemp: 24 },
      { month: "December", avgTemp: 21 },
    ],
  },
  {
    name: "Mexico",
    latitude: 23.6345,
    longitude: -102.5528,
    sea: true,
    mountains: true,
    photo: "https://preview.redd.it/mexico-is-so-hot-that-when-something-is-filmed-there-it-v0-yz2xirwbcgob1.jpg?width=640&crop=smart&auto=webp&s=addcbce59283fe9cd87aa69b69ced8bc3c6e284e",
    description: "A colorful destination with sunny beaches, ancient ruins, and vibrant city life.",
    avgDailyBudget: 80,
    countryCode: "MX",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Proof of funds"],
      notes: "Many nationalities get up to 180 days on arrival. Just show your passport."
    },
    months: [
      { month: "January", avgTemp: 23 },
      { month: "February", avgTemp: 24 },
      { month: "March", avgTemp: 26 },
      { month: "April", avgTemp: 28 },
      { month: "May", avgTemp: 30 },
      { month: "June", avgTemp: 31 },
      { month: "July", avgTemp: 30 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 29 },
      { month: "October", avgTemp: 27 },
      { month: "November", avgTemp: 25 },
      { month: "December", avgTemp: 23 },
    ],
  },
  {
    name: "Egypt",
    latitude: 26.8206,
    longitude: 30.8025,
    sea: true,
    mountains: false,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOpe_G4nWzTP8mGus2uR1B2tZiuQWU0MEFgg&s",
    description: "Home to ancient pyramids, desert landscapes, and warm Mediterranean waters.",
    avgDailyBudget: 65,
    countryCode: "EG",
    visaRequirements: {
      visaRequired: true,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Tourist visa or e-Visa", "Passport photos"],
      notes: "e-Visa available online for most nationalities. Can also obtain on arrival."
    },
    months: [
      { month: "January", avgTemp: 18 },
      { month: "February", avgTemp: 19 },
      { month: "March", avgTemp: 22 },
      { month: "April", avgTemp: 26 },
      { month: "May", avgTemp: 30 },
      { month: "June", avgTemp: 33 },
      { month: "July", avgTemp: 35 },
      { month: "August", avgTemp: 35 },
      { month: "September", avgTemp: 32 },
      { month: "October", avgTemp: 28 },
      { month: "November", avgTemp: 24 },
      { month: "December", avgTemp: 20 },
    ],
  },
  {
    name: "New Zealand",
    latitude: -40.9006,
    longitude: 174.8860,
    sea: true,
    mountains: true,
    photo: "https://t3.ftcdn.net/jpg/03/07/25/28/360_F_307252854_bMQgbmTILZipVQvbI3FlmjxpU53anOLE.jpg",
    description: "A scenic country with dramatic coastlines, fjords, and mountain adventures.",
    avgDailyBudget: 160,
    countryCode: "NZ",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Return ticket", "Proof of funds"],
      notes: "Many nationalities get 3-6 month visitor status on arrival."
    },
    months: [
      { month: "January", avgTemp: 22 },
      { month: "February", avgTemp: 22 },
      { month: "March", avgTemp: 20 },
      { month: "April", avgTemp: 17 },
      { month: "May", avgTemp: 14 },
      { month: "June", avgTemp: 11 },
      { month: "July", avgTemp: 10 },
      { month: "August", avgTemp: 11 },
      { month: "September", avgTemp: 13 },
      { month: "October", avgTemp: 16 },
      { month: "November", avgTemp: 18 },
      { month: "December", avgTemp: 20 },
    ],
  },
  {
    name: "South Africa",
    latitude: -30.5595,
    longitude: 22.9375,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/620737858/photo/cape-town-and-the-12-apostels-from-above.jpg?s=612x612&w=0&k=20&c=WPP0CFtX4y-eHwplbZ1DvPP9bnGjjpz4U4ZZvj8i8Tc=",
    description: "A diverse destination offering wildlife safaris, coastlines, and striking mountain scenery.",
    avgDailyBudget: 95,
    countryCode: "ZA",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 30,
      documents: ["Valid passport", "Return ticket", "Proof of accommodation"],
      notes: "Passport must be valid for at least 30 days after your stay."
    },
    months: [
      { month: "January", avgTemp: 24 },
      { month: "February", avgTemp: 24 },
      { month: "March", avgTemp: 23 },
      { month: "April", avgTemp: 21 },
      { month: "May", avgTemp: 18 },
      { month: "June", avgTemp: 15 },
      { month: "July", avgTemp: 15 },
      { month: "August", avgTemp: 16 },
      { month: "September", avgTemp: 18 },
      { month: "October", avgTemp: 20 },
      { month: "November", avgTemp: 22 },
      { month: "December", avgTemp: 23 },
    ],
  },
  {
    name: "Peru",
    latitude: -9.1900,
    longitude: -75.0152,
    sea: true,
    mountains: true,
    photo: "https://t3.ftcdn.net/jpg/03/12/43/38/360_F_312433849_WZa2vtheKKzxv3x5shBdIe6bSo7R8yCV.jpg",
    description: "Known for the Andes, ancient Inca sites, and lush Amazon rainforest.",
    avgDailyBudget: 90,
    countryCode: "PE",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Proof of funds"],
      notes: "Many nationalities get 90 days on arrival. Valid passport is main requirement."
    },
    months: [
      { month: "January", avgTemp: 18 },
      { month: "February", avgTemp: 18 },
      { month: "March", avgTemp: 19 },
      { month: "April", avgTemp: 19 },
      { month: "May", avgTemp: 18 },
      { month: "June", avgTemp: 16 },
      { month: "July", avgTemp: 15 },
      { month: "August", avgTemp: 15 },
      { month: "September", avgTemp: 16 },
      { month: "October", avgTemp: 17 },
      { month: "November", avgTemp: 18 },
      { month: "December", avgTemp: 18 },
    ],
  },
  {
    name: "Morocco",
    latitude: 31.7917,
    longitude: -7.0926,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/982105760/photo/ait-benhaddou-ancient-city-in-morocco-north-africa.jpg?s=612x612&w=0&k=20&c=RtNjLQio6qFLwhn_MA6J0mCsDsbbE2Wji9mahh-5laM=",
    description: "A North African gem with deserts, historic medinas, and coastal towns.",
    avgDailyBudget: 75,
    countryCode: "MA",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Proof of accommodation"],
      notes: "Many nationalities get 90 days visa-free. Valid passport is essential."
    },
    months: [
      { month: "January", avgTemp: 12 },
      { month: "February", avgTemp: 13 },
      { month: "March", avgTemp: 16 },
      { month: "April", avgTemp: 18 },
      { month: "May", avgTemp: 22 },
      { month: "June", avgTemp: 26 },
      { month: "July", avgTemp: 29 },
      { month: "August", avgTemp: 29 },
      { month: "September", avgTemp: 26 },
      { month: "October", avgTemp: 22 },
      { month: "November", avgTemp: 17 },
      { month: "December", avgTemp: 14 },
    ],
  },
  {
    name: "Argentina",
    latitude: -38.4161,
    longitude: -63.6167,
    sea: true,
    mountains: true,
    photo: "https://t3.ftcdn.net/jpg/02/06/97/20/360_F_206972087_4cOPbdNUqVHCWedpM9Udcge7PBcIyTct.jpg",
    description: "A large country with dramatic landscapes, vibrant culture, and stunning Patagonia.",
    avgDailyBudget: 100,
    countryCode: "AR",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Return ticket", "Yellow fever vaccination (recommended)"],
      notes: "Many nationalities get 90 days visa-free on arrival."
    },
    months: [
      { month: "January", avgTemp: 24 },
      { month: "February", avgTemp: 23 },
      { month: "March", avgTemp: 21 },
      { month: "April", avgTemp: 18 },
      { month: "May", avgTemp: 15 },
      { month: "June", avgTemp: 12 },
      { month: "July", avgTemp: 11 },
      { month: "August", avgTemp: 12 },
      { month: "September", avgTemp: 14 },
      { month: "October", avgTemp: 17 },
      { month: "November", avgTemp: 20 },
      { month: "December", avgTemp: 22 },
    ],
  },
  {
    name: "Croatia",
    latitude: 45.1000,
    longitude: 15.2000,
    sea: true,
    mountains: true,
    photo: "https://t3.ftcdn.net/jpg/02/91/19/48/360_F_291194818_GQAedzWwwEF3uu5WaiKERuKJZH1Y89HE.jpg",
    description: "A beautiful Mediterranean country known for its clear waters, islands, and historic cities.",
    avgDailyBudget: 95,
    countryCode: "HR",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Travel insurance (recommended)"],
      notes: "EU/EEA citizens can enter with ID card. Recent EU member."
    },
    months: [
      { month: "January", avgTemp: 7 },
      { month: "February", avgTemp: 8 },
      { month: "March", avgTemp: 12 },
      { month: "April", avgTemp: 16 },
      { month: "May", avgTemp: 20 },
      { month: "June", avgTemp: 24 },
      { month: "July", avgTemp: 27 },
      { month: "August", avgTemp: 27 },
      { month: "September", avgTemp: 23 },
      { month: "October", avgTemp: 18 },
      { month: "November", avgTemp: 13 },
      { month: "December", avgTemp: 9 },
    ],
  },
  {
    name: "Switzerland",
    latitude: 46.8182,
    longitude: 8.2275,
    sea: false,
    mountains: true,
    photo: "https://t3.ftcdn.net/jpg/02/76/21/66/360_F_276216647_1VykbMxnVdFhEAussykFqv16TATSeSGV.jpg",
    description: "Famous for alpine peaks, charming villages, and picturesque lakes.",
    avgDailyBudget: 170,
    countryCode: "CH",
    visaRequirements: {
      visaRequired: false,
      passportValidityMonths: 3,
      documents: ["Valid passport", "Schengen travel insurance"],
      notes: "EEA citizens can enter with ID card. Part of Schengen Area but not EU."
    },
    months: [
      { month: "January", avgTemp: -1 },
      { month: "February", avgTemp: 0 },
      { month: "March", avgTemp: 4 },
      { month: "April", avgTemp: 8 },
      { month: "May", avgTemp: 13 },
      { month: "June", avgTemp: 17 },
      { month: "July", avgTemp: 19 },
      { month: "August", avgTemp: 19 },
      { month: "September", avgTemp: 15 },
      { month: "October", avgTemp: 10 },
      { month: "November", avgTemp: 5 },
      { month: "December", avgTemp: 1 },
    ],
  },
  {
    name: "India",
    latitude: 20.5937,
    longitude: 78.9629,
    sea: true,
    mountains: true,
    photo: "https://media.istockphoto.com/id/1146517111/photo/taj-mahal-mausoleum-in-agra.jpg?s=612x612&w=0&k=20&c=vcIjhwUrNyjoKbGbAQ5sOcEzDUgOfCsm9ySmJ8gNeRk=",
    description: "A vibrant country with diverse landscapes, rich history, and lively cities.",
    avgDailyBudget: 60,
    countryCode: "IN",
    visaRequirements: {
      visaRequired: true,
      passportValidityMonths: 6,
      documents: ["Valid passport", "Tourist e-Visa", "Passport photos", "Yellow fever vaccination (if applicable)"],
      notes: "e-Visa (eTV) available online for most nationalities. Processing: 2-4 days."
    },
    months: [
      { month: "January", avgTemp: 22 },
      { month: "February", avgTemp: 24 },
      { month: "March", avgTemp: 28 },
      { month: "April", avgTemp: 32 },
      { month: "May", avgTemp: 35 },
      { month: "June", avgTemp: 33 },
      { month: "July", avgTemp: 31 },
      { month: "August", avgTemp: 30 },
      { month: "September", avgTemp: 29 },
      { month: "October", avgTemp: 28 },
      { month: "November", avgTemp: 24 },
      { month: "December", avgTemp: 22 },
    ],
  }
];